import Head from 'next/head';
import Chat from '@/components/Chat';

export default function Home() {
  return (
    <div>
      <Head>
        <title>BabyRobots</title>
        <meta name="description" content="Generated by Memex" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Chat />
      </main>
    </div>
  );
}

