import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>BabyRobots</title>
        <meta name="description" content="Generated by Memex" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello World</h1>
        <p>If you can see this, the page is rendering.</p>
      </main>
    </div>
  );
}

